[versions]
androidx-lifecycle = "2.8.0"
androidx-room = "2.6.1"
androidx-test = "1.5.0"
androidx-test-ext = "1.1.5"
app-compileSdk = "34"
app-minSdk = "26"
app-targetSdk = "26"
app-versionCode = "1"
app-versionName = "1.0"
app-kotlinCompilerExtensionVersion = "1.5.11"
com-github-bumptech-glide = "4.16.0"
com-google-dagger = "2.51.1"
com-squareup-okhttp3 = "4.12.0"
com-squareup-retrofit2 = "2.10.0"
org-jetbrains-kotlin = "1.9.23"
org-jetbrains-kotlinx = "1.8.0"

[libraries]
androidx-activity-activity-compose = "androidx.activity:activity-compose:1.9.0"
androidx-appcompat = "androidx.appcompat:appcompat:1.6.1"
androidx-arch-core-core-testing = "androidx.arch.core:core-testing:2.2.0"
androidx-compose-compose-bom = "androidx.compose:compose-bom:2024.05.00"
androidx-constraintlayout = "androidx.constraintlayout:constraintlayout:2.1.4"
androidx-core-core-ktx = "androidx.core:core-ktx:1.13.1"
androidx-datastore = "androidx.datastore:datastore:1.0.0"
androidx-fragment-fragment-ktx = "androidx.fragment:fragment-ktx:1.7.1"
androidx-hilt-hilt-navigation-compose = "androidx.hilt:hilt-navigation-compose:1.2.0"
androidx-lifecycle-lifecycle-compiler = { module = "androidx.lifecycle:lifecycle-compiler", version.ref = "androidx-lifecycle" }
androidx-lifecycle-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "androidx-lifecycle" }
androidx-lifecycle-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-material = { module = "androidx.compose.material:material" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
androidx-material3 = { module = "androidx.compose.material3:material3" }
androidx-recyclerview = "androidx.recyclerview:recyclerview:1.3.2"
androidx-room-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
androidx-room-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidx-room" }
androidx-room-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidx-room" }
androidx-room-room-rxjava2 = { module = "androidx.room:room-rxjava2", version.ref = "androidx-room" }
androidx-room-room-rxjava3 = { module = "androidx.room:room-rxjava3", version.ref = "androidx-room" }
androidx-room-room-testing = { module = "androidx.room:room-testing", version.ref = "androidx-room" }
androidx-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata" }
androidx-test-core = { module = "androidx.test:core", version.ref = "androidx-test" }
androidx-test-core-ktx = { module = "androidx.test:core-ktx", version.ref = "androidx-test" }
androidx-test-espresso-espresso-core = "androidx.test.espresso:espresso-core:3.5.1"
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-ext" }
androidx-test-ext-junit-ktx = { module = "androidx.test.ext:junit-ktx", version.ref = "androidx-test-ext" }
androidx-ui = { module = "androidx.compose.ui:ui" }
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
com-android-tools-build-gradle = "com.android.tools.build:gradle:8.4.1"
com-github-bumptech-glide = { module = "com.github.bumptech.glide:glide", version.ref = "com-github-bumptech-glide" }
com-github-bumptech-glide-annotations = { module = "com.github.bumptech.glide:annotations", version.ref = "com-github-bumptech-glide" }
com-github-bumptech-glide-compiler = { module = "com.github.bumptech.glide:ksp", version.ref = "com-github-bumptech-glide" }
com-google-android-material = "com.google.android.material:material:1.12.0"
com-google-code-gson = "com.google.code.gson:gson:2.10.1"
com-google-dagger = { module = "com.google.dagger:dagger", version.ref = "com-google-dagger" }
com-google-dagger-dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "com-google-dagger" }
com-google-dagger-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "com-google-dagger" }
com-google-dagger-hilt-android-gradle-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "com-google-dagger" }
com-google-dagger-hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "com-google-dagger" }
com-google-dagger-hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "com-google-dagger" }
com-google-protobuf-protobuf-javalite = "com.google.protobuf:protobuf-javalite:3.18.0"
com-google-protobuf-protoc = "com.google.protobuf:protoc:3.21.7"
com-jakewharton-retrofit-retrofit2-kotlinx-serialization-converter = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter:1.0.0"
com-jakewharton-timber = "com.jakewharton.timber:timber:5.0.1"
com-squareup-moshi-moshi-kotlin = "com.squareup.moshi:moshi-kotlin:1.15.1"
com-squareup-okhttp3-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "com-squareup-okhttp3" }
com-squareup-okhttp3-mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "com-squareup-okhttp3" }
com-squareup-okhttp3-okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "com-squareup-okhttp3" }
com-squareup-retrofit2-adapter-rxjava2 = { module = "com.squareup.retrofit2:adapter-rxjava2", version.ref = "com-squareup-retrofit2" }
com-squareup-retrofit2-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "com-squareup-retrofit2" }
com-squareup-retrofit2-converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "com-squareup-retrofit2" }
com-squareup-retrofit2-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "com-squareup-retrofit2" }
io-mockk = "io.mockk:mockk:1.13.10"
io-reactivex-rxjava2-rxandroid = "io.reactivex.rxjava2:rxandroid:2.1.1"
io-reactivex-rxjava2-rxjava = "io.reactivex.rxjava2:rxjava:2.2.21"
io-reactivex-rxjava2-rxkotlin = "io.reactivex.rxjava2:rxkotlin:2.4.0"
junit = "junit:junit:4.13.2"
org-jetbrains-kotlin-kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "org-jetbrains-kotlin" }
org-jetbrains-kotlin-kotlin-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "org-jetbrains-kotlin" }
org-jetbrains-kotlinx-kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "org-jetbrains-kotlinx" }
org-jetbrains-kotlinx-kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "org-jetbrains-kotlinx" }
org-jetbrains-kotlinx-kotlinx-coroutines-rx2 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-rx2", version.ref = "org-jetbrains-kotlinx" }
org-jetbrains-kotlinx-kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "org-jetbrains-kotlinx" }
org-jetbrains-kotlinx-kotlinx-serialization-json = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.6.3"
org-mockito-mockito-core = "org.mockito:mockito-core:5.12.0"
org-robolectric = "org.robolectric:robolectric:4.12.1"

[plugins]
com-google-protobuf = "com.google.protobuf:0.9.1"
com-google-devtools-ksp = "com.google.devtools.ksp:2.0.0-1.0.22"
