[versions]
androidx-compose-material = "1.6.7"
androidx-compose-ui = "1.6.7"
androidx-databinding = "8.4.1"
androidx-lifecycle = "2.8.0"
androidx-room = "2.6.1"
androidx-test = "1.5.0"
androidx-test-ext = "1.1.5"
app-compileSdk = "34"
app-minSdk = "26"
app-targetSdk = "26"
app-versionCode = "1"
app-versionName = "1.0"
app-kotlinCompilerExtensionVersion = "1.5.11"
com-android-tools-utp = "31.4.1"
com-github-bumptech-glide = "4.16.0"
com-google-dagger = "2.51.1"
com-google-testing-platform = "0.0.9-alpha02"
com-squareup-okhttp3 = "4.12.0"
com-squareup-retrofit2 = "2.10.0"
org-jetbrains-kotlin = "1.9.23"
org-jetbrains-kotlinx = "1.8.0"

[libraries]
androidx-activity-activity-compose = "androidx.activity:activity-compose:1.9.0"
androidx-appcompat = "androidx.appcompat:appcompat:1.6.1"
androidx-arch-core-core-testing = "androidx.arch.core:core-testing:2.2.0"
androidx-compose-compiler = "androidx.compose.compiler:compiler:1.5.11"
androidx-compose-compose-bom = "androidx.compose:compose-bom:2024.05.00"
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "androidx-compose-material" }
androidx-compose-material-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "androidx-compose-material" }
androidx-compose-material3 = "androidx.compose.material3:material3:1.2.1"
androidx-compose-runtime-runtime-livedata = "androidx.compose.runtime:runtime-livedata:1.6.7"
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "androidx-compose-ui" }
androidx-compose-ui-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "androidx-compose-ui" }
androidx-compose-ui-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidx-compose-ui" }
androidx-compose-ui-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "androidx-compose-ui" }
androidx-constraintlayout = "androidx.constraintlayout:constraintlayout:2.1.4"
androidx-core-core-ktx = "androidx.core:core-ktx:1.13.1"
androidx-databinding-databinding-adapters = { module = "androidx.databinding:databinding-adapters", version.ref = "androidx-databinding" }
androidx-databinding-databinding-common = { module = "androidx.databinding:databinding-common", version.ref = "androidx-databinding" }
androidx-databinding-databinding-compiler = { module = "androidx.databinding:databinding-compiler", version.ref = "androidx-databinding" }
androidx-databinding-databinding-ktx = { module = "androidx.databinding:databinding-ktx", version.ref = "androidx-databinding" }
androidx-databinding-databinding-runtime = { module = "androidx.databinding:databinding-runtime", version.ref = "androidx-databinding" }
androidx-datastore = "androidx.datastore:datastore:1.0.0"
androidx-fragment-fragment-ktx = "androidx.fragment:fragment-ktx:1.7.1"
androidx-hilt-hilt-navigation-compose = "androidx.hilt:hilt-navigation-compose:1.2.0"
androidx-lifecycle-lifecycle-compiler = { module = "androidx.lifecycle:lifecycle-compiler", version.ref = "androidx-lifecycle" }
androidx-lifecycle-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "androidx-lifecycle" }
androidx-lifecycle-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-material = { module = "androidx.compose.material:material" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
androidx-material3 = { module = "androidx.compose.material3:material3" }
androidx-recyclerview = "androidx.recyclerview:recyclerview:1.3.2"
androidx-room-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
androidx-room-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidx-room" }
androidx-room-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidx-room" }
androidx-room-room-rxjava2 = { module = "androidx.room:room-rxjava2", version.ref = "androidx-room" }
androidx-room-room-rxjava3 = { module = "androidx.room:room-rxjava3", version.ref = "androidx-room" }
androidx-room-room-testing = { module = "androidx.room:room-testing", version.ref = "androidx-room" }
androidx-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata" }
androidx-test-core = { module = "androidx.test:core", version.ref = "androidx-test" }
androidx-test-core-ktx = { module = "androidx.test:core-ktx", version.ref = "androidx-test" }
androidx-test-espresso-espresso-core = "androidx.test.espresso:espresso-core:3.5.1"
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-ext" }
androidx-test-ext-junit-ktx = { module = "androidx.test.ext:junit-ktx", version.ref = "androidx-test-ext" }
androidx-ui = { module = "androidx.compose.ui:ui" }
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
com-android-tools-build-gradle = "com.android.tools.build:gradle:8.4.1"
com-android-tools-utp-android-device-provider-ddmlib = { module = "com.android.tools.utp:android-device-provider-ddmlib", version.ref = "com-android-tools-utp" }
com-android-tools-utp-android-device-provider-gradle = { module = "com.android.tools.utp:android-device-provider-gradle", version.ref = "com-android-tools-utp" }
com-android-tools-utp-android-test-plugin-host-additional-test-output = { module = "com.android.tools.utp:android-test-plugin-host-additional-test-output", version.ref = "com-android-tools-utp" }
com-android-tools-utp-android-test-plugin-host-apk-installer = { module = "com.android.tools.utp:android-test-plugin-host-apk-installer", version.ref = "com-android-tools-utp" }
com-android-tools-utp-android-test-plugin-host-coverage = { module = "com.android.tools.utp:android-test-plugin-host-coverage", version.ref = "com-android-tools-utp" }
com-android-tools-utp-android-test-plugin-host-device-info = { module = "com.android.tools.utp:android-test-plugin-host-device-info", version.ref = "com-android-tools-utp" }
com-android-tools-utp-android-test-plugin-host-emulator-control = { module = "com.android.tools.utp:android-test-plugin-host-emulator-control", version.ref = "com-android-tools-utp" }
com-android-tools-utp-android-test-plugin-host-logcat = { module = "com.android.tools.utp:android-test-plugin-host-logcat", version.ref = "com-android-tools-utp" }
com-android-tools-utp-android-test-plugin-host-retention = { module = "com.android.tools.utp:android-test-plugin-host-retention", version.ref = "com-android-tools-utp" }
com-android-tools-utp-android-test-plugin-result-listener-gradle = { module = "com.android.tools.utp:android-test-plugin-result-listener-gradle", version.ref = "com-android-tools-utp" }
com-github-bumptech-glide = { module = "com.github.bumptech.glide:glide", version.ref = "com-github-bumptech-glide" }
com-github-bumptech-glide-annotations = { module = "com.github.bumptech.glide:annotations", version.ref = "com-github-bumptech-glide" }
com-github-bumptech-glide-compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "com-github-bumptech-glide" }
com-google-android-material = "com.google.android.material:material:1.12.0"
com-google-code-gson = "com.google.code.gson:gson:2.10.1"
com-google-dagger = { module = "com.google.dagger:dagger", version.ref = "com-google-dagger" }
com-google-dagger-dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "com-google-dagger" }
com-google-dagger-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "com-google-dagger" }
com-google-dagger-hilt-android-gradle-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "com-google-dagger" }
com-google-dagger-hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "com-google-dagger" }
com-google-dagger-hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "com-google-dagger" }
com-google-protobuf-protobuf-javalite = "com.google.protobuf:protobuf-javalite:3.18.0"
com-google-protobuf-protoc = "com.google.protobuf:protoc:3.21.7"
com-google-testing-platform-android-driver-instrumentation = { module = "com.google.testing.platform:android-driver-instrumentation", version.ref = "com-google-testing-platform" }
com-google-testing-platform-android-test-plugin = { module = "com.google.testing.platform:android-test-plugin", version.ref = "com-google-testing-platform" }
com-google-testing-platform-core = { module = "com.google.testing.platform:core", version.ref = "com-google-testing-platform" }
com-google-testing-platform-launcher = { module = "com.google.testing.platform:launcher", version.ref = "com-google-testing-platform" }
com-jakewharton-retrofit-retrofit2-kotlinx-serialization-converter = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter:1.0.0"
com-jakewharton-timber = "com.jakewharton.timber:timber:5.0.1"
com-squareup-moshi-moshi-kotlin = "com.squareup.moshi:moshi-kotlin:1.15.1"
com-squareup-okhttp3-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "com-squareup-okhttp3" }
com-squareup-okhttp3-mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "com-squareup-okhttp3" }
com-squareup-okhttp3-okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "com-squareup-okhttp3" }
com-squareup-retrofit2-adapter-rxjava2 = { module = "com.squareup.retrofit2:adapter-rxjava2", version.ref = "com-squareup-retrofit2" }
com-squareup-retrofit2-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "com-squareup-retrofit2" }
com-squareup-retrofit2-converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "com-squareup-retrofit2" }
com-squareup-retrofit2-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "com-squareup-retrofit2" }
io-mockk = "io.mockk:mockk:1.13.10"
io-reactivex-rxjava2-rxandroid = "io.reactivex.rxjava2:rxandroid:2.1.1"
io-reactivex-rxjava2-rxjava = "io.reactivex.rxjava2:rxjava:2.2.21"
io-reactivex-rxjava2-rxkotlin = "io.reactivex.rxjava2:rxkotlin:2.4.0"
junit = "junit:junit:4.13.2"
org-apache-logging-log4j-log4j-core = "org.apache.logging.log4j:log4j-core:2.17.1"
org-jetbrains-kotlin-kotlin-annotation-processing-gradle = { module = "org.jetbrains.kotlin:kotlin-annotation-processing-gradle", version.ref = "org-jetbrains-kotlin" }
org-jetbrains-kotlin-kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "org-jetbrains-kotlin" }
org-jetbrains-kotlin-kotlin-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "org-jetbrains-kotlin" }
org-jetbrains-kotlin-kotlin-serialization-compiler-plugin-embeddable = { module = "org.jetbrains.kotlin:kotlin-serialization-compiler-plugin-embeddable", version.ref = "org-jetbrains-kotlin" }
org-jetbrains-kotlin-kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "org-jetbrains-kotlin" }
org-jetbrains-kotlinx-kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "org-jetbrains-kotlinx" }
org-jetbrains-kotlinx-kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "org-jetbrains-kotlinx" }
org-jetbrains-kotlinx-kotlinx-coroutines-rx2 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-rx2", version.ref = "org-jetbrains-kotlinx" }
org-jetbrains-kotlinx-kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "org-jetbrains-kotlinx" }
org-jetbrains-kotlinx-kotlinx-serialization-json = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.6.3"
org-mockito-mockito-core = "org.mockito:mockito-core:5.12.0"
org-robolectric = "org.robolectric:robolectric:4.12.1"

[plugins]
android = "android:8.4.1"
android-library = "android-library:8.4.1"
android-reporting = "android-reporting:8.4.1"
com-android-application = "com.android.application:8.4.1"
com-android-asset-pack = "com.android.asset-pack:8.4.1"
com-android-asset-pack-bundle = "com.android.asset-pack-bundle:8.4.1"
com-android-base = "com.android.base:8.4.1"
com-android-dynamic-feature = "com.android.dynamic-feature:8.4.1"
com-android-fused-library = "com.android.fused-library:8.4.1"
com-android-internal-application = "com.android.internal.application:8.4.1"
com-android-internal-asset-pack = "com.android.internal.asset-pack:8.4.1"
com-android-internal-asset-pack-bundle = "com.android.internal.asset-pack-bundle:8.4.1"
com-android-internal-dynamic-feature = "com.android.internal.dynamic-feature:8.4.1"
com-android-internal-fused-library = "com.android.internal.fused-library:8.4.1"
com-android-internal-kotlin-multiplatform-library = "com.android.internal.kotlin.multiplatform.library:8.4.1"
com-android-internal-library = "com.android.internal.library:8.4.1"
com-android-internal-lint = "com.android.internal.lint:8.4.1"
com-android-internal-privacy-sandbox-sdk = "com.android.internal.privacy-sandbox-sdk:8.4.1"
com-android-internal-reporting = "com.android.internal.reporting:8.4.1"
com-android-internal-test = "com.android.internal.test:8.4.1"
com-android-internal-version-check = "com.android.internal.version-check:8.4.1"
com-android-kotlin-multiplatform-library = "com.android.kotlin.multiplatform.library:8.4.1"
com-android-library = "com.android.library:8.4.1"
com-android-lint = "com.android.lint:8.4.1"
com-android-privacy-sandbox-sdk = "com.android.privacy-sandbox-sdk:8.4.1"
com-android-reporting = "com.android.reporting:8.4.1"
com-android-test = "com.android.test:8.4.1"
com-github-ben-manes-versions = "com.github.ben-manes.versions:0.41.0"
com-google-dagger-hilt-android = "com.google.dagger.hilt.android:2.51.1"
com-google-protobuf = "com.google.protobuf:0.9.1"
dagger-hilt-android-plugin = "dagger.hilt.android.plugin:2.51.1"
kotlin = "kotlin:1.9.23"
kotlin-android = "kotlin-android:1.9.23"
kotlin-android-extensions = "kotlin-android-extensions:1.9.23"
kotlin-kapt = "kotlin-kapt:1.9.23"
kotlin-multiplatform = "kotlin-multiplatform:1.9.23"
kotlin-native-cocoapods = "kotlin-native-cocoapods:1.9.23"
kotlin-native-performance = "kotlin-native-performance:1.9.23"
kotlin-parcelize = "kotlin-parcelize:1.9.23"
kotlin-platform-android = "kotlin-platform-android:1.9.23"
kotlin-platform-common = "kotlin-platform-common:1.9.23"
kotlin-platform-js = "kotlin-platform-js:1.9.23"
kotlin-platform-jvm = "kotlin-platform-jvm:1.9.23"
kotlin-scripting = "kotlin-scripting:1.9.23"
kotlinx-serialization = "kotlinx-serialization:1.9.23"
nl-littlerobots-version-catalog-update = "nl.littlerobots.version-catalog-update:0.8.4"
org-jetbrains-kotlin-android = "org.jetbrains.kotlin.android:1.9.23"
org-jetbrains-kotlin-android-extensions = "org.jetbrains.kotlin.android.extensions:1.9.23"
org-jetbrains-kotlin-js = "org.jetbrains.kotlin.js:1.9.23"
org-jetbrains-kotlin-jvm = "org.jetbrains.kotlin.jvm:1.9.23"
org-jetbrains-kotlin-kapt = "org.jetbrains.kotlin.kapt:1.9.23"
org-jetbrains-kotlin-multiplatform = "org.jetbrains.kotlin.multiplatform:1.9.23"
org-jetbrains-kotlin-native-cocoapods = "org.jetbrains.kotlin.native.cocoapods:1.9.23"
org-jetbrains-kotlin-native-performance = "org.jetbrains.kotlin.native.performance:1.9.23"
org-jetbrains-kotlin-platform-android = "org.jetbrains.kotlin.platform.android:1.9.23"
org-jetbrains-kotlin-platform-common = "org.jetbrains.kotlin.platform.common:1.9.23"
org-jetbrains-kotlin-platform-js = "org.jetbrains.kotlin.platform.js:1.9.23"
org-jetbrains-kotlin-platform-jvm = "org.jetbrains.kotlin.platform.jvm:1.9.23"
org-jetbrains-kotlin-plugin-parcelize = "org.jetbrains.kotlin.plugin.parcelize:1.9.23"
org-jetbrains-kotlin-plugin-scripting = "org.jetbrains.kotlin.plugin.scripting:1.9.23"
org-jetbrains-kotlin-plugin-serialization = "org.jetbrains.kotlin.plugin.serialization:1.9.23"
